name = "landing-page-api"
main = "index.ts"
compatibility_date = "2024-01-01"

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "landing_page_leads"
database_id = "058fbcc6-3f09-4844-9f64-308c926800ec" 